dist: xenial
os: linux
language: node_js
python:
  - '12.0'
branches:
  only:
    - master
    - develop
install:
  - npm install
script:
  - npm run test
deploy:
  provider: s3
  bucket: pps-webpage
  local_dir: dist/scout-personal-progression-webapp/
  skip_cleanup: true
  region: us-west-2
  access_key_id:
  secret_access_key:
  on:
    branch: master
notifications:
  email:
    on_failure: always
