dist: xenial
os: linux
language: node_js
node_js:
  - '12'
branches:
  only:
    - master
    - develop
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_script:
  - npm run build
deploy:
  provider: s3
  bucket: pps-webpage
  local_dir: dist/scout-personal-progression-webapp/
  skip_cleanup: true
  region: us-west-2
  access_key_id: AKIAJAZ7FJ6DGPLQGQJQ
  secret_access_key:
    secure: IC4PuFlaS9SngenaAt+fumEauhNi2dqp9rHYbhWr2TlW3+OteHLfN6hObKIvVqvmDQIHi9Zvr0w7wcIIjXeSKVDDPmeV8JhJMxw6cGfOJv5DINjCSN0lV4FpfNcoI7HYMmgSGV77VaEqcjufQrzRjc1JuLWk1pz8zqZPgHTC67frlCgJ7GPhh3W7MY9hH5mUgzphZw1q13E5nVR0NiggUx35/Q6W5eDdO43bPraDJkvO3IVQyWf5j0xVRxaaNw2Zew6nKNJ3e1GYMzEzPUiK6G7GoURgc3EItE24N5xO4YvfY1Jt3XjLI1Dsii7mFfcV1Ge5Rr4HxDqxUNaGDEer1Tq9EJzjtY3Oq+eE0DeTxirnJX2g2Ybakeh+wjTvkctasMstDtRGypLev0cbTc4Q6P38Wh1cSxcdOET9/0xBwsx66jVQEMsEUsmDFtn5I50P4oV75dO9v0bdZmqEvQytUEg5RnuDtguMS9NE6fnoXUQ63h2DVfuHNyuLhbSuGjrDKPIyBkRdvXTQ/TLHNNel2dIdYjhIVgZNyZlWT5j2SATKlAVYQLe7Wocp+ZEerS+soOjPmjDD1eTdvpwhh1A2/kQgo3AzGkckp328uz3PXOq3rZj3aCKHa0l8sHY2PlWxTlOeD4aosx4jm21LysLPIN+PzQtR2sWjm14HTS2jy18=
  on:
    branch: master
notifications:
  email:
    on_failure: always
